
<div class="extended-container">
<div id="container" class="j-container">

<div id="notification"></div><div class="breadcrumb">
        <a href="<?=base_url()?>">Home</a>
         &raquo; <a href="<?=base_url()?>download">Downloads</a>
    </div>
 
<!-- <div id="content"><h1 class="heading-title">Downloads</h1>  <p>Download our latest version catalogues in PDF format. To download catalog you need username and password. To obtain these informations please email us at <a href="mailto:info@innotek.com.pk?subject=PDF%20Password%20Request">info@innotek.com.pk</a></p> -->
<div id="content"><h1 class="heading-title">Downloads</h1>  <p>
    <?=(@$_GET['lang']!='eng') ?  '
Unduh katalog versi terbaru kami dalam format PDF. Untuk mendapatkan informasi ini, silakan email kami di' :  'Download our latest version catalogues in PDF format. To obtain these informations please email us at';?> <a href="mailto:info@innotek.com.pk?subject=PDF%20Password%20Request"><?= $contactus->email ?></a></p>
<p>&nbsp;</p>

<p style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; color: rgb(51, 55, 69); font-family: arial; font-size: 13px;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">&nbsp;CATALOG</strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
&nbsp;</p>

<table align="center" border="0" cellpadding="1" cellspacing="1" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; width: 1000px; border-spacing: 0px; box-sizing: border-box; color: rgb(51, 55, 69); font-family: arial; font-size: 13px;">
    <tbody style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
        <?php foreach ($download->result() as $dn) {
        ?>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img align="center" alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" /><a href="https://admin.gap-id.co.id/upload/download/<?=$dn->pdfUrl?>" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><?= $dn->nama ?>&nbsp;</a>
            &nbsp;</td>
           <!--  <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><a href="<?=base_url()?>../../../upload/download/<?=$dn->pdfUrl?>" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><?= $dn->nama ?>&nbsp;</a>&nbsp;&nbsp; &nbsp; &nbsp;<br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;&nbsp;</strong></td> -->


            <!-- <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">02-Anaesthesia<strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/02.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank">&nbsp;</a>&nbsp; -&nbsp; Updating Soon<br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</strong></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/03.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">03-Trocars &amp; Suction Tube</strong></a><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            <strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">​ &nbsp; &nbsp; &nbsp;&nbsp;</strong></td> -->
    <?php } ?>
        </tr>
        <!-- <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/04.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">04-Scalpel​</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/05.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">05-Scissors</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/06.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">06-Dressing &amp; Tissue Forceps</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/07.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">07-Artery Forceps</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/08.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">08-Cotton Swab Forceps</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/09.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">09-Retractors</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/10.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">10-Probes, Applicators</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/11.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">11-Suture</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/12.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">12-Neurosurgery</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/13.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">13-Dermatology</strong></a><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/14.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">14-Oral Instruments</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">15-Ophthalmology&nbsp; -&nbsp; Updating Soon</strong></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/16.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">16-Otology</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/17.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">17-Rhinology</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/18.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">18-Tonsil</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/19.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">19-Tracheotomy</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/20.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">20-Goitre</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/21.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">21-Cardiovascular</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/22.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">22-Lung Surgery</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/23.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">23-Bone Surgery</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/24.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">24-Intestinal &amp; Stomach</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/25.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">25-Gall Blader</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/26.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">26-Urology</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/27.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">27-Rectum</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/28.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">28-Gynaecology</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/29.pdf" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">29-Obstetrics</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/30.pdf" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); text-decoration-line: none; cursor: pointer; box-sizing: border-box;">30-Maxillofacial</strong></a></td>
        </tr>
        <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="color: rgb(51, 55, 69); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /><br style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;" />
            &nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/32.pdf" style="font-family: arial; font-size: 13px;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; color: rgb(69, 115, 143); cursor: pointer; box-sizing: border-box;">32-Lipo Suction</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="color: rgb(51, 55, 69); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/33.pdf" style="color: rgb(69, 115, 143); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">33-Plaster</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="color: rgb(51, 55, 69); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/34.pdf" style="color: rgb(69, 115, 143); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">34-Asepsis</strong></a></td>
        </tr> -->
       <!--  <tr style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="color: rgb(51, 55, 69); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/35.pdf" style="color: rgb(69, 115, 143); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank"><strong style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box;">35-Sterilization</strong></a></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><img alt="" src="https://www.innotek.com.pk/image/data/pdf-icon.png" style="color: rgb(51, 55, 69); font-family: arial; font-size: 13px; -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; box-sizing: border-box; width: 50px; height: 50px;" /></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;"><strong style="font-family: arial; font-size: 13px; color: rgb(69, 115, 143); -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; cursor: pointer; box-sizing: border-box;"><a href="https://www.innotek.com.pk/dnct/36.pdf" style="color: rgb(69, 115, 143); -webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; margin: 0px; padding: 0px; border: 0px; outline: 0px; text-decoration-line: none; cursor: pointer; box-sizing: border-box;" target="_blank">36-Hollowware</a></strong></td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">&nbsp;</td>
            <td style="-webkit-font-smoothing: antialiased; -webkit-tap-highlight-color: transparent; box-sizing: border-box;">&nbsp;</td>
        </tr> -->
    </tbody>
</table>

<p>&nbsp;</p>

<p><img alt="" src="https://www.innotek.com.pk/web/image/data/innotek/surgicalcat.jpg" /></p>
  <div class="buttons">
    <!-- <div class="right"><a href="<?=base_url()?>" class="button">Continue</a></div> -->
  </div>
  </div>
</div>
</div>